M48
; DRILL file KiCad 10.0.5 date 2026-09-24T00:34:21
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-24T00:34:21-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X124.925Y-107.723
X129.575Y-115.777
T2
X127.394Y-88.773
X173.444Y-94.412
M30
